# Generated by Django 4.0 on 2022-02-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.TextField(max_length=255)),
                ('oneimage', models.ImageField(upload_to='')),
                ('onevote', models.IntegerField(default=0)),
                ('two', models.TextField(max_length=255)),
                ('twoimage', models.ImageField(upload_to='')),
                ('twovote', models.IntegerField(default=0)),
            ],
        ),
    ]
